### ISSUE TITLE
Erro  [LOGIN PROCESSS] - Failed, exiting..

### ISSUE THREAD

**Issue by barrosblucas** [papalardo/alura-download#1]
Estou tentando rodar a aplicação e ela aparece a mensagem de erro:
Eu uso o Windows 10 e executo ele pelo Console do Git Hub Bash

Eu já coloquei o usuário e senha no arquivo env.exemplo
$ node index.js https://cursos.alura.com.br/course/design-pattern-php
[LOGIN PROCESSS] - Authenticating
[LOGIN PROCESSS] - Failed, exiting..

O que pode ser?

**Comment by papalardo** [comment]
No arquivo 'auth.js', na linha 33 coloque para printar o err disparado e depois cole o erro aqui.

**Comment by Shing172** [comment]
> No arquivo 'auth.js', na linha 33 coloque para printar o err disparado e depois cole o erro aqui.

Estou enfrentando o mesmo problema. Perdão pela ignorância, não tenho certeza se é isso que eu deveria fazer:

`[LOGIN PROCESSS] - Authenticating
TypeError: text is not iterable
    at Keyboard.type (C:\Users\Huang\Desktop\alura-download-master\node_modules\
puppeteer\lib\Input.js:111:28)
    at Keyboard.<anonymous> (C:\Users\Huang\Desktop\alura-download-master\node_m
odules\puppeteer\lib\helper.js:83:27)
    at ElementHandle.type (C:\Users\Huang\Desktop\alura-download-master\node_mod
ules\puppeteer\lib\JSHandle.js:281:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DOMWorld.type (C:\Users\Huang\Desktop\alura-download-master\node_mo
dules\puppeteer\lib\DOMWorld.js:291:9)
    at async doLogin (C:\Users\Huang\Desktop\alura-download-master\auth.js:14:9)

    at async C:\Users\Huang\Desktop\alura-download-master\index.js:149:9
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\Users\Huang\Desktop\alura-download-master\n
ode_modules\puppeteer\lib\helper.js:82:19)
    at DOMWorld.type (C:\Users\Huang\Desktop\alura-download-master\node_modules\
puppeteer\lib\DOMWorld.js:291:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async doLogin (C:\Users\Huang\Desktop\alura-download-master\auth.js:14:9)

    at async C:\Users\Huang\Desktop\alura-download-master\index.js:149:9
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Huang\Desktop\alura-download-master\node_modu
les\puppeteer\lib\helper.js:82:19)
    at Page.type (C:\Users\Huang\Desktop\alura-download-master\node_modules\pupp
eteer\lib\Page.js:698:33)
    at doLogin (C:\Users\Huang\Desktop\alura-download-master\auth.js:14:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Huang\Desktop\alura-download-master\index.js:149:9
[LOGIN PROCESSS] - Failed, exiting..`

**Comment by papalardo** [comment]
@Shing172 @barrosblucas 
Parece que não foi configurado as credenciais no arquivo .env. Copie o arquivo .env.example para .env e configure seu login e senha para efetuar o login na plafatorma e então acessar os cursos.

**Comment by Shing172** [comment]
> @Shing172 @barrosblucas
> Parece que não foi configurado as credenciais no arquivo .env. Copie o arquivo .env.example para .env e configure seu login e senha para efetuar o login na plafatorma e então acessar os cursos.

Eu copiei o arquivo .env.example para um outro arquivo .env e editei com os meus dados lá, tudo correto. Porém continua o mesmo erro. 

Ademais, percebi que o seu .env.example tinha uma estrutura diferente, o user e o password estavam em linhas diferentes (o .env.example que eu clonei estavam em uma única linha). Por isso, eu pensei que alterar o formato do meu .env pudesse funcionar. Porém, agora ele diz que as credenciais de login estão incorretas, mesmo que estejam corretas.

Formato do seu .env.example:
![2](https://user-images.githubusercontent.com/65086386/87464737-fe234e80-c5e9-11ea-8d1c-7d468633b8fd.jpg)

Formato do .env.example que eu clonei:
![3](https://user-images.githubusercontent.com/65086386/87464909-47739e00-c5ea-11ea-9781-c1f17866771c.jpg)

Formato que eu alterei do .env para ficar parecido com o seu (que me retornou erro de credenciais incorretas): 
![1](https://user-images.githubusercontent.com/65086386/87464691-ec41ab80-c5e9-11ea-9c46-c6d5bbe6a527.jpg)

**Comment by papalardo** [comment]
@Shing172 
Tem que haver a quebra de linha. Com a quebra de linha apareceu *Credenciais inválidas* ?? 
Se sim, tenta rever as credenciais e apagar possíveis espaços em branco e tente denovo.
Qualquer coisa estou a disposição. 

> Estou sem login no alura, a minha expirou.

**Comment by Shing172** [comment]
> @Shing172
> Tem que haver a quebra de linha. Com a quebra de linha apareceu _Credenciais inválidas_ ??
> Se sim, tenta rever as credenciais e apagar possíveis espaços em branco e tente denovo.
> Qualquer coisa estou a disposição.
> 
> > Estou sem login no alura para testar e ajustar, a minha expirou.

Bom, quando eu edito o .env deixando a quebra de linha e rodo o script, ele me retorna esse erro aqui. Eu verifiquei, não há espaços e o login está 100% correto, copiei do .env e colei no form da Alura pra testar e logou de boa.

![1](https://user-images.githubusercontent.com/65086386/87480146-18b5f180-c603-11ea-9720-d78a55f655d3.jpg)

**Comment by papalardo** [comment]
@Shing172 é desse jeito mesmo.

Envie um e-mail para papalardo94@hotmail.com que te ajudo por lá.

**Comment by barrosblucas** [comment]
Olha eu não sei bem como printar o erro, pois não entendo muito de programação. Mas eu pesquisei na internet e parece que existe um tal comando console.trace e foi o que fiz. Substitui o console.log para console.trace. 

Ele me apresentou a seguinte tela: 
![Screenshot_130](https://user-images.githubusercontent.com/67758594/87785046-79148100-c805-11ea-973f-0b9611d5d0c7.png)

Codigo.
`await page.close()
    } catch (err) {
      	console.trace(
            `[LOGIN PROCESSS] - ${_colors.red('Failed, exiting..')}`
        )
        await browser.close();`

**Comment by papalardo** [comment]
@barrosblucas estamos analisando qual é o problema.

**Comment by papalardo** [comment]
Existia um problema com compatibilidade de variaveis de ambiente e nome de arquivos no Windows. 
Vamos subir uma nova versão em breve para corrigir isto.
